### ISSUE TITLE
Bug: `neotime.DateTime` no longer supported in `py2neo` > 2021.1.5

### ISSUE THREAD

**Issue by cdboer** [DLR-SC/prov2neo#2]
When encoding a provenance graph, the following exception is raised:
```
TypeError: Values of type <class 'neotime.DateTime'> are not supported
```

**Comment by claasdeboer** [comment]
`neotime` has been deprecated in py2neo `2021.2.0`. In `v1.2` we use `py2neo-org/interchange` data types for time encoding instead of `neotime` ones.

Commits concerning this issue:
- d2bc94eb4b96ad0f2b8cfe05b8148e262d222c5c
- bd63f5b67da8344db9df9782f39d682d1478c66d
- b67c40f79001b562428eb40538982c2bdf8907d4
- 9965cd3c401da8e4698ee40fa6db7bb64673e494
